<?php

/**
 * @file
 * Contains happy_alexandrie.module..
 */

/**
 * Implements hook_theme().
 */
function happy_alexandrie_theme($existing, $type, $theme, $path) {
  return [
    'remote_cover' => [
      'variables' => [
        'url' => NULL,
        'title' => '',
      ],
    ],
  ];
}

/**
 * Prepares variables for remote cover template.
 *
 * Default template: remote-cover.html.twig.
 *
 * @param $variables
 *   An associative array containing:
 *   - url: the cover Url.
 *   - title: the book title.
 */
function template_preprocess_remote_cover(&$variables) {
  $variables['url'] = $variables['url']->toString();
}
