<?php

/**
 * @file
 * Contains happy_alexandrie.module..
 */

/**
 * Implements hook_theme().
 */
function happy_alexandrie_theme($existing, $type, $theme, $path) {
  return [
    'remote_cover' => [
      'variables' => [
        'isbn' => '',
        'size' => 'L',
        'title' => '',
      ],
    ],
  ];
}

/**
 * Prepares variables for remote cover template.
 *
 * Default template: remote-cover.html.twig.
 *
 * @param $variables
 *   An associative array containing:
 *   - isbn: the book ISBN.
 *   - size: the size of the cover. Should be S, M or L.
 *   - title: the book title.
 */
function template_preprocess_remote_cover(&$variables) {
  $variables['isbn'] = preg_replace('/[^0-9x]/i', '', $variables['isbn']);
  $variables['size'] = strtoupper($variables['size']);
}
