<?php

/**
 * @file
 * Contains author_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function author_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the author_entity module.
    case 'help.page.author_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function author_entity_theme() {
  $theme = [];
  $theme['author'] = [
    'render element' => 'elements',
    'file' => 'author.page.inc',
    'template' => 'author',
  ];
  $theme['author_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'author.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function author_entity_theme_suggestions_author(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#author'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'author__' . $sanitized_view_mode;
  $suggestions[] = 'author__' . $entity->bundle();
  $suggestions[] = 'author__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'author__' . $entity->id();
  $suggestions[] = 'author__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
