<?php

/**
 * @file
 * Contains happy_alexandrie.module
 */

/**
 * Implements hook_theme().
 */
function happy_alexandrie_theme() {
  $theme = [];

  $theme['happy_cover'] = array(
    'variables' => array('cover_url' => '', 'cover_title' => ''),
    'template' => 'happy-cover',
  );

  return $theme;
}

/**
 * Implements hook_entity_view_alter().
 */
function happy_alexandrie_entity_view_alter(&$build, $type) {
  if (isset($build['#theme']) && $build['#theme'] == 'node') {
    $build['#attached']['library'][] = 'happy_alexandrie/local-favorite';
  }
}